---
title: "Bird Targets"
author: "Jeff Oliver"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, echo = FALSE}
# TODO: Put numbers on map for each site
# TODO: Consider % Checklists with target species?
# TODO: Move timeout to function calls
# TODO: Close connections
# TODO: Consider moving parameters to params specification of YAML header

# Load dependancies
library("jsonlite")
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(ggmap))
suppressMessages(library(httr))
source(file = "functions/eBird-API-2.0.R")

# Load data
# Remove the .RData files if necessary
# current.list.file <- "data/ebird_north_america_year_list.csv"
current.list.file <- "data/ebird_WORLD_year_list.csv"
centers.file <- "data/centers.csv"
# centers.file <- "data/centers-tucson.csv"
output.dir <- "output/"

# Set values for analysis
key <- scan(file = "ebird-2.0-api-key.txt", what = "character")
distance <- 50 # Max distance is 50 km
days.back <- 4
max.targets <- 5 # Maximum number of sites to return per center

# Set a high timeout value, especially necessary for downloading maps
httr::set_config(httr::config(connecttimeout = 30))

# Storage options, mostly for debugging
save.ebird <- TRUE
remove.ebird <- FALSE
```

## Report Details

+ Distance: `r distance` km
+ `r days.back` days back

```{r read-clean, echo = FALSE, message = FALSE, results = "asis", warning = FALSE}
# Read in data & clean as necessary
# Iterate over each center and perform queries as appropriate
# Send results to file

# Read in data & clean
# Read current list, downloaded from eBird site
current.list <- read.csv(file = current.list.file)
# Names come in as dash-separated common - scientific pairs, need to separate
current.list <- SplitNames(data = current.list)

# Read centers with latitude & longitude for each
centers <- read.csv(file = centers.file)

# Iterate over each site
for (center.i in 1:nrow(centers)) {
  center.name <- as.character(centers$center.name[center.i])
  center.name.print <- paste0(toupper(substr(center.name, 1, 1)), 
                              substr(center.name, 2, nchar(center.name)))
  center.lat <- centers[center.i, "lat"]
  center.lng <- centers[center.i, "lng"]
  
  # Check to see if file is stored (mostly for development)
  target.file <- paste0("data/", center.name, "-tmp.RData")
  # If so, use it and don't query eBird; else, query eBird
  if (file.exists(target.file)) {
    message(paste0("Reading eBird data from file for ", center.name.print))
    load(target.file)
  } else {
    message(paste0("Querying eBird for ", center.name.print, " targets."))
    target.list <- TargetList(key = key,
                              center.lat = center.lat,
                              center.lng = center.lng,
                              distance = distance,
                              back = days.back)
  }
  
  # Save the file, mostly for development
  if (save.ebird) {
    save(target.list, file = target.file)
  }
  
  # Make sure we only print up to as many sites as in the targets.list
  num.to.print <- max.targets
  if (length(target.list) < num.to.print) {
    num.to.print <- length(target.list)
  }

  cat(paste0("# ", center.name.print, ", ", distance, " km radius\n"))

  # Draw a map with all the target sites
  # Pull out a little information about each site
  map.data <- lapply(target.list, "[", c("site.name", "num.species", "coordinates"))
  map.data <- map.data[1:num.to.print]
  map.df <- data.frame(site.name = as.character(names(map.data)),
                       num.species = as.vector(unlist(sapply(map.data, "[", "num.species"))),
                       latitude = t(sapply(map.data, "[[", "coordinates"))[, "lat"],
                       longitude = t(sapply(map.data, "[[", "coordinates"))[, "lng"])
  # Oddly, this does *not* work if we try to do it when initializing df...
  map.df$site.name <- as.character(map.df$site.name)
  
  # Order by decreasing # species (could have been done already)
  map.df <- map.df[order(map.df$num.species, decreasing = TRUE), ]
  rownames(map.df) <- NULL
  
  # Make a column with abbreviated name and unseen species count
  map.df$print.name <- paste0(rownames(map.df), " - ", 
                              substr(x = map.df$site.name,
                                     start = 1,
                                     stop =  10))
  map.df$print.name <- paste0(map.df$print.name, " (", map.df$num.species, ")")
  
  map.bounds <- c(floor(min(c(map.df$longitude, center.lng))),
                  floor(min(c(map.df$latitude, center.lat))),
                  ceiling(max(c(map.df$longitude, center.lng))),
                  ceiling(max(c(map.df$latitude, center.lat))))
  
  # TODO: Move mapping to functions file and place inside a conditional in case
  # retrival via ggmap::get_map times out
  center.map <- get_map(location = map.bounds, 
                        source = "stamen", 
                        maptype = "terrain")
  
  targets.map <- ggmap(center.map) +
    geom_point(data = map.df,
               mapping = aes(x = longitude, y = latitude, color = print.name),
               size = 3) +
   scale_color_brewer(name = "Site", palette = "Dark2") +
    theme_bw() +
    xlab(label = "Longitude") +
    ylab(label = "Latitude")
  
  print(targets.map)
  Sys.sleep(time = 2.0) # So we're not hammering on the map server

  cat("\n") # To ensure new line after map
    
  # Iterate over the desired number of target sites for this center and print
  for (site.i in 1:num.to.print) {
    # Extract the current target list
    target <- target.list[[site.i]]
    
    CreateSiteMarkdown(target = target, site.number = site.i)
  }
  
  cat("\n***\n")

  # Remove the eBird file if we don't want to save it  
  if(remove.ebird & file.exists(target.file)) {
    file.remove(target.file)
  }
}
```


